apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: webapp-chart-trigger-template
  namespace: webapp
spec:
  params:
    - name: git-revision
      default: main
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: webapp-chart-ci-triggered-
      spec:
        pipelineRef:
          name: webapp-chart-ci
        params:
          - name: repo-url
            value: http://gitea-http.gitea.svc.cluster.local:3000/admin/webapp-chart.git
          - name: revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: chart-workspace
        taskRunTemplate:
          serviceAccountName: pipeline-sa
          podTemplate:
            tolerations:
              - operator: Exists
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: webapp-chart-trigger-binding
  namespace: webapp
spec:
  params:
    - name: git-revision
      value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webapp-chart-listener
  namespace: webapp
spec:
  serviceAccountName: pipeline-sa
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            tolerations:
              - operator: Exists
  triggers:
    - name: gitea-push
      bindings:
        - ref: webapp-chart-trigger-binding
      template:
        ref: webapp-chart-trigger-template
